import 'package:flutter/material.dart';
final String SIGN_IN = 'signin';
final String SIGN_UP ='signup';
final String SPLASH_SCREEN ='splashscreen';
final String RECOVER = 'recover';
final String NGO_SIGN_UP = 'ngosignup';
final String HOME_PAGE = 'homepage';
final String SETTINGS = 'settings';
final String STORE_DETAILS = 'storedetails';
const PrimaryColor = Colors.teal;
const SecondaryColor = Colors.tealAccent;